export interface MockCategory {
  id: string;
  name: string;
  slug: string;
  icon: string;
  subcategories: string[];
}

export interface MockProduct {
  id: string;
  name: string;
  slug: string;
  price: number;
  mrp: number;
  unit: string;
  imageUrl: string;
  categoryId: string;
  subcategory: string;
  missionTags: string[];
  inStock: boolean;
  rating: number;
  description: string;
}

export interface MockMissionDefinition {
  key: string;
  displayName: string;
  icon: string;
  requiredSubcategories: string[];
  optionalSubcategories: string[];
  suggestedProductQueries: string[];
}

export const MOCK_CATEGORIES: MockCategory[] = [
  {
    id: 'cat-1',
    name: 'Dairy, Bread & Eggs',
    slug: 'dairy-bread-eggs',
    icon: '🥛',
    subcategories: ['Milk & Cream', 'Bread & Bakery', 'Eggs', 'Butter & Cheese', 'Yogurt & Dahi'],
  },
  {
    id: 'cat-2',
    name: 'Fruits & Vegetables',
    slug: 'fruits-vegetables',
    icon: '🥬',
    subcategories: ['Fresh Vegetables', 'Fresh Fruits', 'Exotics & Herbs', 'Organic Produce'],
  },
  {
    id: 'cat-3',
    name: 'Atta, Rice & Dal',
    slug: 'atta-rice-dal',
    icon: '🌾',
    subcategories: ['Atta & Flours', 'Rice & Rice Products', 'Dals & Pulses', 'Edible Oils & Ghee'],
  },
  {
    id: 'cat-4',
    name: 'Snacks & Munchies',
    slug: 'snacks-munchies',
    icon: '🍿',
    subcategories: ['Chips & Namkeen', 'Biscuits & Cookies', 'Nuts & Dry Fruits', 'Chocolates & Sweets'],
  },
  {
    id: 'cat-5',
    name: 'Cold Drinks & Juices',
    slug: 'cold-drinks-juices',
    icon: '🥤',
    subcategories: ['Soft Drinks', 'Fruit Juices', 'Energy Drinks', 'Water & Soda', 'Tea & Coffee'],
  },
  {
    id: 'cat-6',
    name: 'Instant & Frozen Food',
    slug: 'instant-frozen-food',
    icon: '🍜',
    subcategories: ['Noodles & Pasta', 'Ready to Eat', 'Frozen Veg Snacks', 'Ice Creams'],
  },
  {
    id: 'cat-7',
    name: 'Personal Care',
    slug: 'personal-care',
    icon: '🧴',
    subcategories: ['Bath & Body', 'Hair Care', 'Oral Care', 'Skin Care & Hygiene'],
  },
  {
    id: 'cat-8',
    name: 'Cleaning & Household',
    slug: 'cleaning-household',
    icon: '🧹',
    subcategories: ['Detergents & Dishes', 'Surface Cleaners', 'Tissues & Disposables'],
  },
  {
    id: 'cat-9',
    name: 'Baby Care',
    slug: 'baby-care',
    icon: '👶',
    subcategories: ['Baby Diapers & Wipes', 'Baby Food', 'Baby Bath & Skin'],
  },
  {
    id: 'cat-10',
    name: 'Pet Care',
    slug: 'pet-care',
    icon: '🐶',
    subcategories: ['Dog Food & Treats', 'Cat Food', 'Pet Grooming & Litter'],
  },
];

export const MOCK_PRODUCTS: MockProduct[] = [
  // Dairy, Bread & Eggs & Proteins
  {
    id: 'prod-101',
    name: 'Amul Taaza Toned Fresh Milk',
    slug: 'amul-taaza-toned-fresh-milk',
    price: 28,
    mrp: 30,
    unit: '500 ml',
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Milk & Cream',
    missionTags: ['breakfast', 'tea_time', 'monthly_grocery'],
    inStock: true,
    rating: 4.8,
    description: 'Pasteurised toned milk enriched with Vitamin A & D. Perfect for daily tea, coffee, and cereal.',
  },
  {
    id: 'prod-102',
    name: 'Britannia 100% Whole Wheat Bread',
    slug: 'britannia-whole-wheat-bread',
    price: 45,
    mrp: 50,
    unit: '400 g',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Bread & Bakery',
    missionTags: ['breakfast', 'quick_snack'],
    inStock: true,
    rating: 4.7,
    description: 'Healthy and wholesome 100% whole wheat bread baked fresh daily. Rich in dietary fiber.',
  },
  {
    id: 'prod-103',
    name: 'Farm Fresh White Eggs (Pack of 6)',
    slug: 'farm-fresh-white-eggs-6',
    price: 52,
    mrp: 60,
    unit: '6 units',
    imageUrl: 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Eggs & Paneer',
    missionTags: ['breakfast', 'high_protein', 'meal_prep', 'dinner_prep'],
    inStock: true,
    rating: 4.9,
    description: 'Fresh farm eggs packed with natural protein and essential nutrients.',
  },
  {
    id: 'prod-106',
    name: 'Fresh Malai Paneer Block (200g)',
    slug: 'fresh-malai-paneer-200g',
    price: 95,
    mrp: 110,
    unit: '200 g',
    imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Eggs & Paneer',
    missionTags: ['meal_prep', 'dinner_prep', 'high_protein'],
    inStock: true,
    rating: 4.9,
    description: 'Rich, soft, and fresh cottage cheese malai paneer block, ideal for curry and grilling.',
  },
  {
    id: 'prod-107',
    name: 'Amul Fresh Soft Paneer Cubes',
    slug: 'amul-fresh-soft-paneer',
    price: 90,
    mrp: 105,
    unit: '200 g',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Eggs & Paneer',
    missionTags: ['meal_prep', 'dinner_prep', 'high_protein'],
    inStock: true,
    rating: 4.8,
    description: 'Pre-cut fresh soft paneer cubes ready for quick cooking.',
  },
  {
    id: 'prod-108',
    name: 'Organic Soya Tofu Block 250g',
    slug: 'organic-soya-tofu-block',
    price: 75,
    mrp: 90,
    unit: '250 g',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Eggs & Paneer',
    missionTags: ['meal_prep', 'fitness_nutrition', 'high_protein'],
    inStock: true,
    rating: 4.7,
    description: 'High-protein organic plant-based soya tofu block.',
  },
  {
    id: 'prod-109',
    name: 'Fresh Chicken Breast Boneless 500g',
    slug: 'fresh-chicken-breast-500g',
    price: 199,
    mrp: 230,
    unit: '500 g',
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Eggs & Paneer',
    missionTags: ['meal_prep', 'fitness_nutrition', 'high_protein', 'dinner_prep'],
    inStock: true,
    rating: 4.9,
    description: 'Tender, skinless and boneless fresh chicken breast rich in lean protein.',
  },
  {
    id: 'prod-110',
    name: 'Organic Brown Eggs (Pack of 6)',
    slug: 'organic-brown-eggs-6',
    price: 75,
    mrp: 90,
    unit: '6 units',
    imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Eggs & Paneer',
    missionTags: ['meal_prep', 'breakfast', 'fitness_nutrition', 'high_protein'],
    inStock: true,
    rating: 4.8,
    description: 'Farm-fresh free-range brown eggs packed with Omega-3 and natural protein.',
  },
  {
    id: 'prod-104',
    name: 'Amul Pasteurised Salted Butter',
    slug: 'amul-pasteurised-butter',
    price: 56,
    mrp: 60,
    unit: '100 g',
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Butter & Cheese',
    missionTags: ['breakfast', 'dinner_prep'],
    inStock: true,
    rating: 4.9,
    description: 'Iconic Amul salted butter made from pure milk fat. Gives incredible flavor to toasts and cooking.',
  },
  {
    id: 'prod-105',
    name: 'Amul Dahi Cup',
    slug: 'amul-dahi-cup',
    price: 35,
    mrp: 40,
    unit: '400 g',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Milk & Curd',
    missionTags: ['dinner_prep', 'meal_prep', 'monthly_grocery'],
    inStock: true,
    rating: 4.7,
    description: 'Thick, creamy and delicious curd made from pasteurised milk.',
  },

  // Cereals & Spreads
  {
    id: 'prod-111',
    name: 'Quaker Rolled Oats 1kg',
    slug: 'quaker-rolled-oats-1kg',
    price: 190,
    mrp: 220,
    unit: '1 kg',
    imageUrl: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Breakfast Cereals',
    missionTags: ['breakfast', 'fitness_nutrition'],
    inStock: true,
    rating: 4.8,
    description: '100% whole grain rolled oats for a high-fiber nutritious breakfast.',
  },
  {
    id: 'prod-112',
    name: "Bagrry's Crunchy Muesli Fruit & Nut",
    slug: 'bagrrys-crunchy-muesli',
    price: 299,
    mrp: 350,
    unit: '400 g',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-1',
    subcategory: 'Breakfast Cereals',
    missionTags: ['breakfast'],
    inStock: true,
    rating: 4.8,
    description: 'Crunchy oat muesli with real almonds, raisins, and honey.',
  },

  // Fruits & Vegetables
  {
    id: 'prod-201',
    name: 'Fresh Red Tomatoes (Hybrid)',
    slug: 'fresh-red-tomatoes-hybrid',
    price: 38,
    mrp: 48,
    unit: '1 kg',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-2',
    subcategory: 'Fresh Vegetables',
    missionTags: ['dinner_prep', 'meal_prep', 'monthly_grocery'],
    inStock: true,
    rating: 4.6,
    description: 'Firm, juicy hybrid red tomatoes sourced directly from local farms.',
  },
  {
    id: 'prod-202',
    name: 'Fresh Red Onions',
    slug: 'fresh-red-onions',
    price: 32,
    mrp: 40,
    unit: '1 kg',
    imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cf?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-2',
    subcategory: 'Fresh Vegetables',
    missionTags: ['dinner_prep', 'meal_prep', 'monthly_grocery'],
    inStock: true,
    rating: 4.7,
    description: 'Essential cooking ingredient. Crisp and flavorful red onions.',
  },
  {
    id: 'prod-203',
    name: 'Robusta Bananas',
    slug: 'robusta-bananas',
    price: 42,
    mrp: 50,
    unit: '1 kg (5-6 pcs)',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-2',
    subcategory: 'Fresh Fruits',
    missionTags: ['breakfast', 'workout_snack'],
    inStock: true,
    rating: 4.8,
    description: 'Naturally ripened sweet Robusta bananas rich in potassium and energy.',
  },
  {
    id: 'prod-204',
    name: 'Crisp Shimla Apples',
    slug: 'crisp-shimla-apples',
    price: 140,
    mrp: 180,
    unit: '4 pcs (~600g)',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-2',
    subcategory: 'Fresh Fruits',
    missionTags: ['healthy_snack', 'breakfast'],
    inStock: true,
    rating: 4.9,
    description: 'Juicy, sweet and crunchy Shimla red apples.',
  },

  // Atta, Rice & Dal & Spices
  {
    id: 'prod-301',
    name: 'Aashirvaad Shuddh Chakki Atta',
    slug: 'aashirvaad-shuddh-chakki-atta',
    price: 245,
    mrp: 275,
    unit: '5 kg',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-3',
    subcategory: 'Flours & Grains',
    missionTags: ['meal_prep', 'dinner_prep', 'monthly_grocery'],
    inStock: true,
    rating: 4.9,
    description: '100% pure whole wheat flour processed with traditional 3-step chakki process for soft rotis.',
  },
  {
    id: 'prod-302',
    name: 'Fortune Sunlite Refined Sunflower Oil',
    slug: 'fortune-sunlite-sunflower-oil',
    price: 135,
    mrp: 155,
    unit: '1 L pouch',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-3',
    subcategory: 'Spices & Oils',
    missionTags: ['meal_prep', 'dinner_prep', 'monthly_grocery'],
    inStock: true,
    rating: 4.8,
    description: 'Light and healthy refined sunflower oil rich in Vitamin E.',
  },
  {
    id: 'prod-305',
    name: 'Everest Garam Masala Powder 100g',
    slug: 'everest-garam-masala-100g',
    price: 85,
    mrp: 95,
    unit: '100 g',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-3',
    subcategory: 'Spices & Oils',
    missionTags: ['meal_prep', 'dinner_prep'],
    inStock: true,
    rating: 4.9,
    description: 'Authentic Indian blend of 13 aromatic spices for rich curry flavor.',
  },
  {
    id: 'prod-303',
    name: 'Tata Sampann Unpolished Toor Dal',
    slug: 'tata-sampann-unpolished-toor-dal',
    price: 165,
    mrp: 190,
    unit: '1 kg',
    imageUrl: 'https://images.unsplash.com/photo-1585996877201-5483042f446d?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-3',
    subcategory: 'Pulses & Dal',
    missionTags: ['meal_prep', 'dinner_prep', 'monthly_grocery'],
    inStock: true,
    rating: 4.8,
    description: 'High protein unpolished yellow arhar toor dal without synthetic polish.',
  },
  {
    id: 'prod-304',
    name: 'Daawat Rozana Super Basmati Rice',
    slug: 'daawat-rozana-super-basmati-rice',
    price: 399,
    mrp: 450,
    unit: '5 kg',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-3',
    subcategory: 'Flours & Grains',
    missionTags: ['meal_prep', 'dinner_prep', 'monthly_grocery'],
    inStock: true,
    rating: 4.7,
    description: 'Aromatic medium long grain basmati rice ideal for everyday cooking.',
  },

  // Disposables, Cleaners & Adjacent Gaps
  {
    id: 'prod-801',
    name: 'Cleanwrap Kitchen Rubber Gloves (Medium)',
    slug: 'cleanwrap-kitchen-rubber-gloves',
    price: 99,
    mrp: 120,
    unit: '1 pair',
    imageUrl: 'https://images.unsplash.com/photo-1584634731339-252c581abfc5?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-8',
    subcategory: 'Cleaners & Fresheners',
    missionTags: ['meal_prep', 'house_cleaning'],
    inStock: true,
    rating: 4.7,
    description: 'Durable non-slip kitchen gloves for washing dishes & food prep.',
  },
  {
    id: 'prod-802',
    name: 'Vim Dishwash Liquid Gel Lemon 500ml',
    slug: 'vim-dishwash-liquid-gel-500ml',
    price: 115,
    mrp: 130,
    unit: '500 ml',
    imageUrl: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-8',
    subcategory: 'Cleaners & Fresheners',
    missionTags: ['meal_prep', 'house_cleaning'],
    inStock: true,
    rating: 4.9,
    description: 'Powerful degreasing lemon dishwash gel formula.',
  },
  {
    id: 'prod-804',
    name: 'Oddy Uniwrap Food Cling Wrap & Foil',
    slug: 'oddy-uniwrap-food-cling-wrap',
    price: 145,
    mrp: 175,
    unit: '20 meters',
    imageUrl: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-8',
    subcategory: 'Disposables',
    missionTags: ['meal_prep'],
    inStock: true,
    rating: 4.8,
    description: 'Food-grade wrapping foil & wrap to keep meal prep fresh.',
  },

  // Snacks & Munchies
  {
    id: 'prod-401',
    name: "Lay's India's Magic Masala Potato Chips",
    slug: 'lays-indias-magic-masala',
    price: 20,
    mrp: 20,
    unit: '50 g',
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-4',
    subcategory: 'Chips & Namkeen',
    missionTags: ['movie_night', 'guest_arrival', 'party'],
    inStock: true,
    rating: 4.9,
    description: 'Crunchy potato chips seasoned with authentic Indian spices.',
  },
  {
    id: 'prod-402',
    name: 'Doritos Nacho Cheese Tortilla Chips',
    slug: 'doritos-nacho-cheese',
    price: 50,
    mrp: 50,
    unit: '82.5 g',
    imageUrl: 'https://images.unsplash.com/photo-1518013031184-4638a168aa49?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-4',
    subcategory: 'Chips & Namkeen',
    missionTags: ['movie_night', 'guest_arrival', 'party'],
    inStock: true,
    rating: 4.8,
    description: 'Boldly cheesy, triangular corn tortilla chips.',
  },
  {
    id: 'prod-403',
    name: 'Cadbury Dairy Milk Silk Chocolate Bar',
    slug: 'cadbury-dairy-milk-silk',
    price: 175,
    mrp: 190,
    unit: '150 g',
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-4',
    subcategory: 'Chocolates',
    missionTags: ['movie_night', 'sweet_craving'],
    inStock: true,
    rating: 4.9,
    description: 'Irresistibly smooth and creamy milk chocolate bar.',
  },

  // Cold Drinks & Juices
  {
    id: 'prod-501',
    name: 'Coca-Cola Soft Drink Bottle',
    slug: 'coca-cola-bottle',
    price: 40,
    mrp: 40,
    unit: '750 ml',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-5',
    subcategory: 'Soft Drinks & Juices',
    missionTags: ['movie_night', 'guest_arrival', 'party'],
    inStock: true,
    rating: 4.8,
    description: 'Refreshing carbonated soft drink served ice cold.',
  },
  {
    id: 'prod-502',
    name: 'Real Fruit Power 100% Mixed Fruit Juice',
    slug: 'real-fruit-power-mixed-fruit',
    price: 110,
    mrp: 130,
    unit: '1 L Tetra',
    imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-5',
    subcategory: 'Soft Drinks & Juices',
    missionTags: ['breakfast', 'guest_arrival'],
    inStock: true,
    rating: 4.7,
    description: 'Delicious blend of 9 fruits with no added preservatives or colors.',
  },

  // Baby Care
  {
    id: 'prod-901',
    name: 'Pampers All-Round Protection Baby Diapers (M)',
    slug: 'pampers-baby-diapers-medium',
    price: 699,
    mrp: 899,
    unit: '42 diapers',
    imageUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-9',
    subcategory: 'Diapers & Wipes',
    missionTags: ['baby_care'],
    inStock: true,
    rating: 4.9,
    description: 'Ultra-absorbent diaper pants with anti-rash lotion and 12-hour overnight dryness.',
  },
  {
    id: 'prod-902',
    name: "Johnson's Baby Gentle Skincare Wipes",
    slug: 'johnsons-baby-wipes',
    price: 185,
    mrp: 210,
    unit: '72 wipes',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-9',
    subcategory: 'Diapers & Wipes',
    missionTags: ['baby_care'],
    inStock: true,
    rating: 4.8,
    description: 'Soft wipes enriched with lotion for baby delicate skin.',
  },
  {
    id: 'prod-903',
    name: 'Nestlé Cerelac Wheat Apple Baby Food',
    slug: 'nestle-cerelac-wheat-apple',
    price: 245,
    mrp: 270,
    unit: '300 g',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-9',
    subcategory: 'Baby Food',
    missionTags: ['baby_care'],
    inStock: true,
    rating: 4.9,
    description: 'Fortified baby cereal with milk & nutrients for babies 6+ months.',
  },

  // Pet Care
  {
    id: 'prod-1001',
    name: 'Pedigree Adult Dry Dog Food (Chicken & Vegetables)',
    slug: 'pedigree-adult-dry-dog-food',
    price: 380,
    mrp: 440,
    unit: '1.2 kg',
    imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-10',
    subcategory: 'Pet Food',
    missionTags: ['pet_care'],
    inStock: true,
    rating: 4.8,
    description: 'Complete nutritional dry kibble for adult dogs enriched with Omega 6 & Zinc.',
  },
  {
    id: 'prod-1002',
    name: 'Whiskas Ocean Fish Wet Cat Food Pouch',
    slug: 'whiskas-ocean-fish-wet-cat-food',
    price: 50,
    mrp: 60,
    unit: '85 g',
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-10',
    subcategory: 'Pet Food',
    missionTags: ['pet_care'],
    inStock: true,
    rating: 4.8,
    description: 'Tasty wet cat food pouch rich in real fish protein and essential taurine.',
  },
  {
    id: 'prod-1003',
    name: 'Bentonite Clumping Cat Litter Lavender 5kg',
    slug: 'bentonite-clumping-cat-litter',
    price: 450,
    mrp: 550,
    unit: '5 kg',
    imageUrl: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-10',
    subcategory: 'Pet Hygiene',
    missionTags: ['pet_care'],
    inStock: true,
    rating: 4.7,
    description: 'Fast-clumping, low-dust natural bentonite pet cat litter.',
  },
  {
    id: 'prod-1004',
    name: 'Himalaya Erina EP Pet Grooming Shampoo',
    slug: 'himalaya-erina-ep-pet-shampoo',
    price: 260,
    mrp: 295,
    unit: '200 ml',
    imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=400&q=80',
    categoryId: 'cat-10',
    subcategory: 'Pet Hygiene',
    missionTags: ['pet_care'],
    inStock: true,
    rating: 4.9,
    description: 'Ayurvedic anti-tick & flea pet grooming shampoo.',
  },
];

export const MOCK_MISSIONS: MockMissionDefinition[] = [
  {
    key: 'breakfast',
    displayName: 'Breakfast Prep',
    icon: '☕',
    requiredSubcategories: ['Bread & Bakery', 'Milk & Cream', 'Eggs'],
    optionalSubcategories: ['Butter & Cheese', 'Tea & Coffee', 'Poha & Breakfast Mixes', 'Napkins & Disposables'],
    suggestedProductQueries: ['bread', 'eggs', 'milk', 'muesli', 'napkins'],
  },
  {
    key: 'meal_prep',
    displayName: 'Kitchen Meal Prep',
    icon: '🔪',
    requiredSubcategories: ['Fresh Vegetables', 'Fresh Fruits'],
    optionalSubcategories: ['Paneer & Tofu', 'Edible Oils & Ghee', 'Chopping & Storage Tools', 'Kitchen Gloves & Bags'],
    suggestedProductQueries: ['vegetables', 'paneer', 'oil', 'cling wrap', 'garbage bags'],
  },
  {
    key: 'dinner_prep',
    displayName: 'Dinner Cooking',
    icon: '🥘',
    requiredSubcategories: ['Atta & Flours', 'Fresh Vegetables'],
    optionalSubcategories: ['Dals & Pulses', 'Edible Oils & Ghee', 'Spices & Masalas', 'Dishwash Liquid'],
    suggestedProductQueries: ['atta', 'tomatoes', 'onions', 'toor dal', 'masala', 'dishwash'],
  },
  {
    key: 'monthly_grocery',
    displayName: 'Monthly Pantry Restock',
    icon: '🛒',
    requiredSubcategories: ['Atta & Flours', 'Rice & Rice Products', 'Edible Oils & Ghee'],
    optionalSubcategories: ['Dals & Pulses', 'Personal Care', 'Cleaning & Household', 'Bulk Snack Bundles'],
    suggestedProductQueries: ['atta', 'rice', 'oil', 'shampoo', 'detergent'],
  },
  {
    key: 'movie_night',
    displayName: 'Movie Night Snacks',
    icon: '🍿',
    requiredSubcategories: ['Chips & Namkeen', 'Soft Drinks'],
    optionalSubcategories: ['Chocolates & Sweets', 'Ice Creams', 'Tissues & Disposables'],
    suggestedProductQueries: ['chips', 'coca-cola', 'chocolate', 'popcorn', 'tissues'],
  },
  {
    key: 'guest_arrival',
    displayName: 'Hosting Guests',
    icon: '👥',
    requiredSubcategories: ['Chips & Namkeen', 'Soft Drinks'],
    optionalSubcategories: ['Frozen Starters', 'Fruit Juices', 'Disposables & Napkins', 'Ice Cubes'],
    suggestedProductQueries: ['chips', 'coca-cola', 'juice', 'disposable plates', 'ice cubes'],
  },
  {
    key: 'baby_care',
    displayName: 'Baby Essentials',
    icon: '👶',
    requiredSubcategories: ['Baby Diapers & Wipes'],
    optionalSubcategories: ['Baby Food', 'Baby Bath & Skin', 'Baby Detergent'],
    suggestedProductQueries: ['diapers', 'baby wipes', 'cerelac', 'baby soap'],
  },
  {
    key: 'pet_care',
    displayName: 'Pet Care',
    icon: '🐶',
    requiredSubcategories: ['Dog Food & Treats'],
    optionalSubcategories: ['Cat Food', 'Pet Grooming & Litter', 'Pet Toys & Stain Cleaner'],
    suggestedProductQueries: ['pedigree', 'dog food', 'pet shampoo', 'litter'],
  },
];

export const MOCK_COUPONS: Record<string, { code: string; discountAmount?: number; discountPercent?: number; maxDiscount?: number; minTotal: number }> = {
  WELCOME100: { code: 'WELCOME100', discountAmount: 100, minTotal: 299 },
  MISSION20: { code: 'MISSION20', discountPercent: 20, maxDiscount: 150, minTotal: 199 },
};
